/**
 * @file RTC.c
 * @author Eshan Wells (eshanwells@gmail.com)
 * @brief driver for MCP7940
 * @version 0.1
 * @date 2023-04-11
 * 
 * @copyright Copyright (c) 2023
 * 
 */

#include "RTC.h"

//!YOOOO IM HAVING ISSUES PASSING A STRUCT THROUGH TO my I2C FUNCTIONS.
//! I MAY WANNA MAKE NEW FUNCTIONS WITH POINTER MAGIC OR SOMETHING?
//! COPY JOHN'S IIC CODE? THAT SEEMED TO HANDLE IT WELL
//! OR AS AN INTERMEDIATE STEP JUST TURN THE STRUCT INTO AN ARRAY. BUT I DON'T LIKE THAT :(
//! ANYWAY GET THIS SORTED I'M ON A ROLL HERE.
